[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "ApexNav"
version = "0.1"
authors = [
    {name = "Zager-Zhang"},
]
description = "ApexNav"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numba == 0.60.0",
    "rospkg == 1.5.1",
    "numpy == 1.23.5",
    "flask == 3.0.3",
    "seaborn == 0.13.2",
    "open3d == 0.18.0",
    "prettytable >= 3.12.0",
    "opencv-python == 4.6.0.66",
    "moviepy == 1.0.3",
    "ultralytics==8.3.209",
    "clip @ git+https://github.com/ultralytics/CLIP.git@488e81a6711eea7346872b46ea928b367da8889d",
    "habitat2ros @ file:./habitat2ros",
]

[project.optional-dependencies]
dev = [
    "pre-commit >= 3.1.1",
    "pytest >= 7.2.1",
    "pytest-cov >= 4.0.0",
]
